name: Cache Dependencies
description: 'Caches Yarn dependencies with two-level strategy'
author: 'gratisv'

branding:
  icon: 'archive'
  color: 'purple'

inputs:
  enable-cache:
    description: 'Enable dependency caching'
    required: false
    default: 'true'

  yarn-cache-dir:
    description: 'Yarn cache directory path'
    required: true

  node-version:
    description: 'Node.js version (for cache key)'
    required: false
    default: 'latest'

  yarn-version:
    description: 'Yarn version (for cache key)'
    required: false
    default: 'latest'

outputs:
  cache-hit:
    description: 'Whether cache was restored via primary key (true/false)'
    value: ${{ steps.cache-deps.outputs.cache-hit }}

  cache-key:
    description: 'Primary cache key used'
    value: ${{ steps.cache-deps.outputs.cache-primary-key }}

  cache-matched-key:
    description: 'Actual key that was restored (primary or restore-key fallback)'
    value: ${{ steps.cache-deps.outputs.cache-matched-key }}

runs:
  using: composite
  steps:
    - name: Cache Yarn dependencies
      id: cache-deps
      if: inputs.enable-cache == 'true'
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ${{ inputs.yarn-cache-dir }}
          node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ inputs.yarn-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ inputs.yarn-version }}-
          ${{ runner.os }}-node-${{ inputs.node-version }}-
          ${{ runner.os }}-

    - name: Cache summary
      if: inputs.enable-cache == 'true'
      shell: bash
      run: |
        HIT="${{ steps.cache-deps.outputs.cache-hit }}"
        PRIMARY="${{ steps.cache-deps.outputs.cache-primary-key }}"
        MATCHED="${{ steps.cache-deps.outputs.cache-matched-key }}"
        PATHS="${{ inputs.yarn-cache-dir }}, node_modules"

        if [[ "$HIT" == "true" ]]; then
          STATUS_LOG="âœ…  HIT"
          STATUS_MD="âœ… HIT"
        elif [[ -n "$MATCHED" ]]; then
          STATUS_LOG="ðŸ”¶  PARTIAL (restore-key)"
          STATUS_MD="ðŸ”¶ PARTIAL (restore-key)"
        else
          STATUS_LOG="âš ï¸  MISS"
          STATUS_MD="âš ï¸ MISS"
        fi

        COL1=16
        COL2=50

        pad_right() { printf "%-${1}s" "${2}"; }

        border_top() { printf "â”Œ"; printf 'â”€%.0s' $(seq 1 $((COL1 + 2))); printf "â”¬"; printf 'â”€%.0s' $(seq 1 $((COL2 + 2))); printf "â”\n"; }
        border_mid() { printf "â”œ"; printf 'â”€%.0s' $(seq 1 $((COL1 + 2))); printf "â”¼"; printf 'â”€%.0s' $(seq 1 $((COL2 + 2))); printf "â”¤\n"; }
        border_bot() { printf "â””"; printf 'â”€%.0s' $(seq 1 $((COL1 + 2))); printf "â”´"; printf 'â”€%.0s' $(seq 1 $((COL2 + 2))); printf "â”˜\n"; }
        row() { printf "â”‚ %s â”‚ %s â”‚\n" "$(pad_right $COL1 "$1")" "$(pad_right $COL2 "${2:0:$COL2}")"; }

        border_top
        row "ðŸ“¦ Cache Deps" "Summary"
        border_mid
        row "Status"   "$STATUS_LOG"
        row "OS"       "${{ runner.os }}"
        row "Node.js"  "${{ inputs.node-version }}"
        row "Yarn"     "${{ inputs.yarn-version }}"
        row "Primary key" "$PRIMARY"
        if [[ -n "$MATCHED" && "$MATCHED" != "$PRIMARY" ]]; then
          row "Restored from" "$MATCHED"
        fi
        row "Paths" "$PATHS"
        border_bot

        {
          echo "## ðŸ“¦ Cache Dependencies"
          echo ""
          echo "| Property | Value |"
          echo "|:---------|:------|"
          echo "| Status | $STATUS_MD |"
          echo "| OS | \`${{ runner.os }}\` |"
          echo "| Node.js | \`${{ inputs.node-version }}\` |"
          echo "| Yarn | \`${{ inputs.yarn-version }}\` |"
          echo "| Primary key | \`$PRIMARY\` |"
          if [[ -n "$MATCHED" && "$MATCHED" != "$PRIMARY" ]]; then
            echo "| Restored from | \`$MATCHED\` |"
          fi
          echo "| Paths | \`${{ inputs.yarn-cache-dir }}\`, \`node_modules\` |"
        } >> "$GITHUB_STEP_SUMMARY"
