name: Format

on:
  workflow_call:

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node & Yarn
        uses: ./actions/prepare

      - name: Run format check
        run: yarn fmt:check
