name: Format

on:
  workflow_call:

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node & Yarn
        uses: ./actions/prepare

      - name: Run format check
        run: yarn fmt:check
